name: Java CI
on: push
env:
  docker_username: ${{ secrets.DOCKERHUB_UN }}
  docker_password: ${{ secrets.DOCKERHUB_PW }}
  GIT_COMMIT: ${{ github.GIT_COMMIT }}
jobs:
  clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: .
  build:
    runs-on: ubuntu-latest
    needs: clone-down
    container: gradle:6-jdk11
    steps:
      - name: Download code
        uses: actions/download-artifact@v2
        with:
          name: app
          path: .
      - name: Build-app
        run: chmod +x ci/build-app.sh && ci/build-app.sh
      - name: Test-app
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: .
  docker:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
    - name: Download code
      uses: actions/download-artifact@v1
      with:
        name: app
        path: .
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ env.docker_username }}
        password: ${{ env.docker_password }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: $docker_username/micronaut-app:1.0-${GIT_COMMIT::8}